import UIProvider from "@/context/UIProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import TopNavbar from "@/components/TopNavbar";
import AppProvider from "@/context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <UIProvider>
          <AppProvider>
            <div className="">{children}</div>
          </AppProvider>
        </UIProvider>
      </body>
    </html>
  );
}
